### PR TITLE
Add two scripts to run all containers: one locally and one on EC2

### PR DESCRIPTION
**Pull request by tzach**

### CODE REVIEW

**Comment by tzach** [comment]
Why is it simpler?
Instead of 3 trivial scripts, one "private" and two public, we will have two, with one of them more complex:
1. have a condition, default value
2. can be called directly or in directly (confusing)

**Comment by avikivity** [comment]
Can we determine automatically if we're on EC2?

**Comment by tzach** [comment]
> Can we determine automatically if we're on EC2?

This is not unique to EC2. It need to be done with any monitoring server you want to access externally, each time with the proper external IP.

**Comment by avikivity** [comment]
Usually there's no difference between the external IP and the host IP.

btw, why is it even needed?  can't the thing use relative URLs?

**Comment by tzach** [comment]
> Usually there's no difference between the external IP and the host IP.

EC2 is the usual use case these days :)

> btw, why is it even needed? can't the thing use relative URLs?

The IP is used from the **browser**, not from the Tessra server.

**Comment by avikivity** [comment]
Usually the browser supplies the host name, and any links the server provide will be relative, so the server does not need to know its own host name.

**Comment by tgrabiec** [comment]
@avikivity tessera doesn't assume that graphite runs on the same machine as tessera, so it requires the address to be provided.

**Comment by avikivity** [comment]
What a shame. I'd propose adding an option so it can make that assumption, but it's not worth it.

**Pull request merged**
